In [ ]:
!pip install datasets
!pip install openpyxl
!pip install -q -U google-genai
# !pip install transformers
# !pip install accelerate
# !pip install peft
# !pip install bitsandbytes
# Imports

# Imports

In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import sys

# Call models
from src.call_models import bedrock_connect, call_claude_bedrock
from src.call_models import google_connect, call_gemini, all_string_gemini_config, all_int_gemini_config
from src.translate_func import claude_translation, gemini_translation

# Datasets
from prompts import mmlu_prompts
from src.benchmarks_code import mmlu
# Access keys
from my_access_keys import google_access_key, aws_access_key, aws_secret_key

# .csv utils
from src.save_utils import add_dataset_to_csv

# Remove annoying warning
from IPython.core.display_functions import display

In [2]:
bedrock_client = bedrock_connect(aws_access_key, aws_secret_key)
google_client = google_connect(google_access_key)

# Get Dataset

In [3]:
mmlu_dataset = mmlu.get_mmlu_datasets()
# mmlu_dataset['mmlu_test'] = mmlu_dataset['mmlu_test']
size = mmlu_dataset['mmlu_test'].num_rows
mmlu_dataset['mmlu_test'] = mmlu_dataset['mmlu_test'] #.select(np.arange(0, size, 90))

df_mmlu_full = pd.DataFrame(mmlu_dataset['mmlu_test'])
df_mmlu_part = pd.DataFrame(mmlu_dataset['mmlu_test'].select(np.arange(0, size, 90)))
df_mmlu_part.index = np.arange(0, size, 90)

print(df_mmlu_full.shape, df_mmlu_part.shape)
# display(df_mmlu_full.head(2))
# display(df_mmlu_part.head(2))

mmlu_dataset

(14042, 4) (157, 4)

{'mmlu_test': Dataset({
     features: ['question', 'subject', 'choices', 'answer'],
     num_rows: 14042
 })}

## How much needed from each subject?

In [4]:
df_mmlu_labeled = pd.read_csv('labeled_files/mmlu_test_labeled_gradio.csv')
df_mmlu_labeled.shape

(177, 18)

In [5]:
need_from_each = pd.Series(index=df_mmlu_full['subject'].unique(), data=20)

remove = df_mmlu_part[(df_mmlu_labeled.iloc[:df_mmlu_part.shape[0]]['rating'] != 'SKIP').values]['subject'].value_counts()
remove = remove.reindex(need_from_each.index, fill_value=0)
need_from_each -= remove
need_from_each = need_from_each.sort_values(ascending=False)
display(need_from_each.head(3))
print()
display(need_from_each.tail(3))

electrical_engineering          20
econometrics                    20
high_school_computer_science    20
dtype: int64

miscellaneous       13
moral_scenarios     12
professional_law     6
dtype: int64

In [6]:
use_subjects = [
    "professional_psychology",
    "high_school_psychology",
    "high_school_macroeconomics",
    "elementary_mathematics",
    "prehistory",
    "philosophy",
    "high_school_biology",
    "nutrition",
    "professional_accounting",
    "professional_medicine",
    "high_school_mathematics",
    "clinical_knowledge",
    "security_studies",
    "high_school_microeconomics",
    "high_school_world_history",
    "conceptual_physics",
    "marketing",
    "human_aging",
    "high_school_statistics",
    "high_school_chemistry",
    "sociology",
    "high_school_geography",
    "college_medicine",
    "world_religions",
    "virology",
    "high_school_european_history",
    "logical_fallacies",
    "astronomy",
    "high_school_physics",
    "electrical_engineering",
    "college_biology",
    "anatomy",
    "human_sexuality",
    "formal_logic",
    "international_law",
    "econometrics",
    "machine_learning",
    "public_relations",
    "management",
    "college_physics",
    "college_computer_science",
    "college_mathematics",
    "global_facts",
    "high_school_computer_science",
    "computer_security",
    "abstract_algebra",
    "business_ethics",
    "college_chemistry",
    "medical_genetics",
]

side_subjects = [
    "professional_law",
    "moral_scenarios",
    "miscellaneous",
    "moral_disputes",
    "high_school_us_history",
    "high_school_government_and_politics",
    "jurisprudence",
    "us_foreign_policy",
]

In [7]:
need_from_each[need_from_each.index.isin(use_subjects)].sum(), need_from_each[need_from_each.index.isin(side_subjects)].sum()

(892, 124)

In [8]:
df_mmlu_full = df_mmlu_full[~df_mmlu_full.index.isin(df_mmlu_part.index)]
df_mmlu_full.shape

(13885, 4)

In [9]:
needed_use_only = need_from_each[need_from_each.index.isin(use_subjects)]
print(needed_use_only.shape)

df_mmlu_full['subject_cnt'] = df_mmlu_full.groupby('subject').cumcount()
take_indices = df_mmlu_full[df_mmlu_full['subject'].isin(use_subjects)]
take_indices = take_indices[take_indices.apply(lambda x: x['subject_cnt'] < needed_use_only.loc[x['subject']], axis=1)]
print(take_indices.shape)
mmlu_dataset['mmlu_test'] = mmlu_dataset['mmlu_test'].select(take_indices.index)
mmlu_dataset

(49,)
(892, 5)

{'mmlu_test': Dataset({
     features: ['question', 'subject', 'choices', 'answer'],
     num_rows: 892
 })}

In [30]:
take_indices.head(500)['subject'].value_counts()

subject
electrical_engineering          20
high_school_computer_science    20
econometrics                    20
anatomy                         19
computer_security               19
college_physics                 19
college_computer_science        19
college_mathematics             19
global_facts                    19
business_ethics                 19
college_chemistry               19
college_biology                 19
high_school_european_history    19
formal_logic                    19
abstract_algebra                18
astronomy                       18
college_medicine                18
clinical_knowledge              18
high_school_chemistry           18
conceptual_physics              18
high_school_geography           18
high_school_physics             18
high_school_macroeconomics      17
high_school_biology             17
high_school_microeconomics      17
high_school_mathematics         17
elementary_mathematics          16
high_school_psychology           3
Name: count, dtype: int64

In [10]:
(pd.DataFrame(mmlu_dataset['mmlu_test'])['subject'].value_counts().sort_index() == needed_use_only.sort_index()).all()

True

## Create save file

In [11]:
mmlu_dataset

{'mmlu_test': Dataset({
     features: ['question', 'subject', 'choices', 'answer'],
     num_rows: 892
 })}

In [12]:
mmlu_dataset['mmlu_test'] = mmlu_dataset['mmlu_test'].skip(300).select(list(range(147)) + list(range(148, 200)))
mmlu_file_name = 'compare_csv/mmlu_test_main_sub_301-500.csv'

In [13]:
mmlu_dataset

{'mmlu_test': Dataset({
     features: ['question', 'subject', 'choices', 'answer'],
     num_rows: 199
 })}

df = add_dataset_to_csv(mmlu_file_name, 'original', mmlu_dataset['mmlu_test'], mmlu.mmlu_sample_to_dict)
text_df = add_dataset_to_csv(mmlu_file_name[:-4] + '-text.csv', 'original', mmlu_dataset['mmlu_test'], mmlu.mmlu_sample_to_dict)
display(df.head(2))
display(text_df.head(2))

In [15]:
df = pd.read_csv(mmlu_file_name)
text_df = pd.read_csv(mmlu_file_name[:-4] + '-text.csv')
display(df.head(2))
display(text_df.head(2))

                                            original
0  <question> Select the best English interpretat...
1  <question>Construct a complete truth table for...

                                            original
0  <question> Select the best English interpretat...
1  <question>Construct a complete truth table for...

In [16]:
df.shape, text_df.shape

((199, 1), (199, 1))

# Run Translation

## Claude

small = {}
small['mmlu_test'] = mmlu_dataset['mmlu_test'].skip(124).take(1)
small

!ls checkpoints/

!cp checkpoints/claude_mmlu_val_25.pkl checkpoints/save_101_125.pkl
!cp checkpoints/claude_mmlu_val_25_text.pkl checkpoints/save_101_125_text.pkl

exp_name = 'claude_v1_refine'

hebrew_datasets, text_output = claude_translation(
    bedrock_client,
    mmlu_dataset,
    # small,
    mmlu_prompts.MMLU_INSTRUCT_V1_CLAUDE_REFINE,
    mmlu_prompts.MMLU_FEW_SHOTS,
    mmlu_prompts.MMLU_FORMAT_REFINE,
    mmlu.mmlu_sample_to_dict,
    mmlu.mmlu_dict_to_sample,
)

import pickle
from datasets import Dataset, concatenate_datasets

with open('checkpoints/save_100.pkl', 'rb') as f:
    lst_1 = pickle.load(f)
with open('checkpoints/save_100_text.pkl', 'rb') as f:
    lst_1_text = pickle.load(f)

with open('checkpoints/save_101_125.pkl', 'rb') as f:
    lst_2 = pickle.load(f)
with open('checkpoints/save_101_125_text.pkl', 'rb') as f:
    lst_2_text = pickle.load(f)
len(lst_1), len(lst_1_text), len(lst_2), len(lst_2_text)

lst_1 = Dataset.from_list(lst_1)
lst_2 = Dataset.from_list(lst_2)

hebrew_datasets['mmlu_val'] = concatenate_datasets([lst_1, lst_2, hebrew_datasets['mmlu_val']])
text_output['mmlu_val'] = lst_1_text + lst_2_text + text_output['mmlu_val']

In [10]:
%%time

# exp_name = 'claude_3-7_v7_thinking'
exp_name = 'claude_thinking_v2'

hebrew_datasets, text_output = claude_translation(
    bedrock_client,
    mmlu_dataset,
    # small,
    mmlu_prompts.MMLU_INSTRUCT_CLAUDE_V2,
    mmlu_prompts.MMLU_FEW_SHOTS,
    mmlu_prompts.MMLU_FORMAT,
    mmlu.mmlu_sample_to_dict,
    mmlu.mmlu_dict_to_sample,
    if_four=False,
)

Translating mmlu_test...

  0%|          | 0/157 [00:00<?, ?it/s]

CPU times: user 1.11 s, sys: 161 ms, total: 1.27 s
Wall time: 41min 55s

In [11]:
def len_mat(text):
    pattern = r"<(?!response_format\b)([^>]+)>(.*?)</\1>"
    matches = re.findall(pattern, text, re.DOTALL)
    return len(matches)

In [12]:
import re
pd.Series([len_mat(i) for i in text_output['mmlu_test']]).value_counts()

6     129
5      24
10      2
15      1
11      1
Name: count, dtype: int64

In [20]:
pd.Series([len_mat(i.split('Text:')[-1]) for i in text_output['mmlu_test']]).value_counts()

6    132
5     25
Name: count, dtype: int64

In [21]:
print(text_output['mmlu_test'][3])

Thinking:
I need to translate this astronomy multiple-choice question about Jupiter's magnetic field from English to Hebrew. Let's break down the key terms and translate them accurately:

1. "Jupiter's magnetic field" - "השדה המגנטי של צדק"
2. "20000 times stronger" - "חזק פי 20000"
3. "Earth's magnetic field" - "השדה המגנטי של כדור הארץ"
4. "traps charged particles" - "לוכד חלקיקים טעונים"
5. "Io's volcanoes" - "הרי הגעש של איו" (Io is one of Jupiter's moons)
6. "plasma torus" - "טורוס פלזמה" (scientific term that would likely be used as-is in Hebrew with Hebrew pronunciation)
7. "auroral displays" - "מופעי זוהר" or "תצוגות זוהר קוטבי"
8. "north and south poles" - "הקטבים הצפוני והדרומי"
9. "switches polarity" - "מחליף קוטביות"
10. "every 11 years" - "כל 11 שנים"

This is a universal subject (astronomy/planetary science), so I will perform a direct translation without needing to adapt to an Israeli context.

Now for the full translation:

Question: "מה אינו נכון לגבי השדה המגנטי של צדק?"

Option A: "הוא חזק פי 20000 בערך מהשדה המגנטי של כדור הארץ"
Option B: "הוא לוכד חלקיקים טעונים מהרי הגעש של איו ב'טורוס פלזמה' סביב כוכב הלכת"
Option C: "הוא גורם לתצוגות זוהר קוטבי מרהיבות בקטבים הצפוני והדרומי של צדק"
Option D: "הוא מחליף קוטביות כל 11 שנים"

Text:
<subject>אסטרונומיה</subject>
<question>מה אינו נכון לגבי השדה המגנטי של צדק?</question>
<choice_a>הוא חזק פי 20000 בערך מהשדה המגנטי של כדור הארץ</choice_a>
<choice_b>הוא לוכד חלקיקים טעונים מהרי הגעש של איו ב"טורוס פלזמה" סביב כוכב הלכת</choice_b>
<choice_c>הוא גורם לתצוגות זוהר קוטבי מרהיבות בקטבים הצפוני והדרומי של צדק</choice_c>
<choice_d>הוא מחליף קוטביות כל 11 שנים</choice_d>

In [14]:
df = add_dataset_to_csv(mmlu_file_name, exp_name, hebrew_datasets['mmlu_test'], mmlu.mmlu_sample_to_dict)
df.head(2)

,original,claude_thinking_v2
0,<question>Find the degree for the given field ...,<question>מצאו את המעלה עבור הרחבת השדה הנתונה...
1,<question>Statement 1 | If a finite group has ...,<question>היגד 1 | אם חבורה סופית היא מסדר n א...

In [15]:
text_df[exp_name + ' text'] = text_output['mmlu_test']
text_df.to_csv(mmlu_file_name[:-4] + '-text.csv', index=False)
text_df.head(2)

,original,claude_thinking_v2 text
0,<question>Find the degree for the given field ...,Thinking:\nI need to translate the given Engli...
1,<question>Statement 1 | If a finite group has ...,Thinking:\nI need to translate the given abstr...

## Gemini

In [17]:
small = {}
small['mmlu_test'] = mmlu_dataset['mmlu_test'].skip(125)
small

{'mmlu_test': Dataset({
     features: ['question', 'subject', 'choices', 'answer'],
     num_rows: 74
 })}

In [18]:
exp_name = 'gemini_pro_think_v1'

hebrew_datasets, text_output = gemini_translation(
    google_client,
    # mmlu_dataset,
    small,
    mmlu_prompts.MMLU_INSTRUCT_V1_GEMINI,
    mmlu_prompts.MMLU_FEW_SHOTS,
    # mmlu_prompts.MMLU_FEW_SHOTS[:2221] + mmlu_prompts.MMLU_FEW_SHOTS[-19:],
    mmlu.mmlu_sample_to_dict,
    mmlu.mmlu_dict_to_sample,
    if_pro=True,
    think_bud=6_000,
)

Translating mmlu_test...

  0%|          | 0/74 [00:00<?, ?it/s]

In [19]:
hebrew_datasets

{'mmlu_test': Dataset({
     features: ['question', 'subject', 'choices', 'answer', 'translation_status'],
     num_rows: 74
 })}

In [21]:
import pickle
from datasets import Dataset, concatenate_datasets

with open('gemini_cp/ck - gemini_mmlu_test_125.pkl', 'rb') as f:
    lst_1 = pickle.load(f)
with open('gemini_cp/ck - gemini_mmlu_test_125_text.pkl', 'rb') as f:
    lst_1_text = pickle.load(f)

len(lst_1), len(lst_1_text)

(125, 125)

In [22]:
lst_1 = Dataset.from_list(lst_1)

hebrew_datasets['mmlu_test_fixed'] = concatenate_datasets([lst_1, hebrew_datasets['mmlu_test']])
text_output['mmlu_test_fixed'] = lst_1_text + text_output['mmlu_test']

In [23]:
hebrew_datasets['mmlu_test_fixed']

Dataset({
    features: ['question', 'subject', 'choices', 'answer', 'translation_status'],
    num_rows: 199
})

In [24]:
for i in range(0, 200, 20):
    print(i)
    display(mmlu_dataset['mmlu_test'][i])
    display(hebrew_datasets['mmlu_test'][i])
    print()
    print('-' * 50)
    print()

0

{'question': ' Select the best English interpretation of the given proposition, using the following translation key: Ax: x is an apartment Hx: x is a house Lx: x is large Bxy: x is bigger than y (∃x)[(Ax • Lx) • (∃y)(Hy • Bxy)]',
 'subject': 'formal_logic',
 'choices': ['Some large houses are bigger than some apartments.',
  'Some houses are bigger than all large apartments.',
  'Some large apartments are bigger than some houses.',
  'Some houses are bigger thatn some large apartments.'],
 'answer': 2}

{'question': 'איזו מהדתות הבאות התפתחה ראשונה?',
 'subject': 'high_school_geography',
 'choices': ['בודהיזם', 'נצרות', 'אסלאם', 'הינדואיזם'],
 'answer': 'ד',
 'translation_status': 'Success'}

--------------------------------------------------

20

{'question': 'Which of the following countries generated the most total energy from solar sources in 2019?',
 'subject': 'global_facts',
 'choices': ['China', 'United States', 'Germany', 'Japan'],
 'answer': 0}

{'question': "אם מחומש P שקודקודיו הם (– 2, – 4), (– 4, 1), (–1, 4), (2, 4), ו-(3, 0) משוקף ביחס לישר y = x לקבלת מחומש חדש, 'P, אז אחד מקודקודיו של 'P הוא",
 'subject': 'high_school_mathematics',
 'choices': ['(0, – 3)', '(4, 1)', '(2, 2)', '(– 4, –2)'],
 'answer': 'ד',
 'translation_status': 'Success'}

--------------------------------------------------

40

{'question': 'Convergent evolution is best exemplified by which of the following?',
 'subject': 'high_school_biology',
 'choices': ['The pectoral fins of fish and the front legs of cats',
  'The presence of a notochord in all chordate embryos',
  'The wings of an insect and the wings of a bird',
  'The leaves of an oak tree and the spines of a cactus'],
 'answer': 2}

{'question': 'מהי אחת הסיבות לכך שהממשלה פועלת נגד קנוניה בין חברות גדולות באותו ענף?',
 'subject': 'high_school_microeconomics',
 'choices': ['רמות התפוקה בקנוניה נוטות לעלות, מה שמעלה את המחיר מעל לרמות תחרותיות.',
  'עודף הצרכן יורד כאשר המחיר נדחף כלפי מטה.',
  'רמות התפוקה בקנוניה נוטות לרדת, מה שמוריד את המחיר לרמות תחרותיות.',
  'מקסום רווחים משותף גורם לחברה לאובדן של עודף הצרכן, כאשר המחיר עולה מעל לרמות תחרותיות.'],
 'answer': 'ד',
 'translation_status': 'Success'}

--------------------------------------------------

60

{'question': "Hund's rule requires that",
 'subject': 'high_school_chemistry',
 'choices': ['no two electrons can have the same four quantum numbers',
  'no two electrons with the same spin can occupy an orbital',
  'no two electrons can occupy separate orbitals',
  'no two electrons can pair up if there is an empty orbital at the same energy level available'],
 'answer': 3}

{'question': 'מהי העבודה הנדרשת כדי לטעון קבל של 10 µF להפרש פוטנציאלים של 100 V?',
 'subject': 'high_school_physics',
 'choices': ['0.005 J', '0.01 J', '0.05 J', '0.1 J'],
 'answer': 'ג',
 'translation_status': 'Success'}

--------------------------------------------------

80

{'question': "In Python 3, what is the output of print tuple[0] if tuple = ( 'abcd', 786 , 2.23, 'john', 70.2 )?",
 'subject': 'high_school_computer_science',
 'choices': ["( 'abcd', 786 , 2.23, 'john', 70.2 )",
  'abcd',
  'Error',
  'None of the above.'],
 'answer': 1}

IndexError: Invalid key: 80 is out of bounds for size 74

In [25]:
df = add_dataset_to_csv(mmlu_file_name, exp_name, hebrew_datasets['mmlu_test_fixed'], mmlu.mmlu_sample_to_dict)
text_df[exp_name + ' text'] = text_output['mmlu_test_fixed']
text_df.to_csv(mmlu_file_name[:-4] + '-text.csv', index=False)
display(df.head(2))
display(text_df.head(2))

,original,gemini_pro_think_v1
0,<question> Select the best English interpretat...,<question>בחרו את הפרשנות הטובה ביותר לפסוק הנ...
1,<question>Construct a complete truth table for...,"<question>בנו טבלת אמת מלאה עבור הטיעון הבא, ו..."

,original,gemini_pro_think_v1 text
0,<question> Select the best English interpretat...,"**Okay, let's break down this translation task..."
1,<question>Construct a complete truth table for...,**Final Thoughts and Translation Justification...